package vu.lt.mybatis.model;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.NAME
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOOK.LIBRARY_ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    private Integer libraryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.ID
     *
     * @return the value of PUBLIC.BOOK.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.ID
     *
     * @param id the value for PUBLIC.BOOK.ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.NAME
     *
     * @return the value of PUBLIC.BOOK.NAME
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.NAME
     *
     * @param name the value for PUBLIC.BOOK.NAME
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOOK.LIBRARY_ID
     *
     * @return the value of PUBLIC.BOOK.LIBRARY_ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public Integer getLibraryId() {
        return libraryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOOK.LIBRARY_ID
     *
     * @param libraryId the value for PUBLIC.BOOK.LIBRARY_ID
     *
     * @mbg.generated Sun Mar 03 13:45:02 EET 2019
     */
    public void setLibraryId(Integer libraryId) {
        this.libraryId = libraryId;
    }
}